### ISSUE TITLE
Crash when trying to change color of multiple nodes

### ISSUE THREAD

**Issue by pulkomandy** [Paradoxianer/ProjectConceptor#60]
- Start ProjectConceptor
- Add 4 nodes
- Select the nodes by drag rectangle around them
- Click the color button

ProjectConceptor crashes. No debug report because Debugger also crashed when trying to investigate, but the issue is reproductible.

**Comment by Paradoxianer** [comment]
Thanks... will look into this later..

**Comment by Paradoxianer** [comment]
I really cant find the source of the problem... maybe i need to switch back from using set to BList...

I had crazy errors like... not shure why... because when i wrote the recepie for Haiporter i tested it and it worked.. :(
ProjectConceptor: ../haiku-git/src/system/libroot/posix/malloc_hoard2/superblock.h:171:class BPrivate::block * BPrivate::superblock::getBlock(): getNumAvailable() == 0

**Comment by Paradoxianer** [comment]
Somehow the Node::Pattern Message is kind of added as a own Node... makes no sense... but brings me closer to the solution
BMessage(0x0) {
        FillColor = int32(0xffbeb498 or -4279144)
        BorderColor = int32(0xff000000 or -16777216)
        PenSize = float(0.0000)
        DrawingMode = int8(0xa or 10 or '
')
        HighColor = int32(0xff000000 or -16777216)
        LowColor = int32(0xff808080 or -8355712)
        Pattern = (type = 'PATN')(size = 8)
        ProjectConceptor::doc = (type = 'PNTR')(size = 4)
        GraphEditor0::Renderer = (type = 'PNTR')(size = 4)
}
